import "./globals.css";
import { Open_Sans } from "next/font/google";
import Header from "@/components/Header";

const openSans = Open_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Botanical Plant Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />
        <main className="px-4 sm:px-8 lg:px-20">{children}</main>
      </body>
    </html>
  );
}
