import {
  ArrowRight,
  Carrot,
  ChevronRight,
  Fingerprint,
  Flower,
  Github,
  LeafIcon,
  MenuIcon,
  Search,
  Send,
  ShoppingCart,
  ShovelIcon,
  SproutIcon,
  Sun,
  TreePineIcon,
  X,
} from "lucide-react";

export const Icons = {
  logo: Carrot, //temporary
  search: Search,
  X: X,
  cart: ShoppingCart,
  menu: MenuIcon,
  arrowRight: ArrowRight,
  leaf: LeafIcon,
  sprout: SproutIcon,
  tree: TreePineIcon,
  github: Github,
  fingerPrint: Fingerprint,
  send: Send,
  sun: Sun,
  chevronRight: ChevronRight,
  shovel: ShovelIcon,
  flower: Flower,
};
