import {
  ArrowRight,
  Carrot,
  ChevronRight,
  Disc,
  Fingerprint,
  Github,
  Heart,
  LeafIcon,
  MenuIcon,
  Search,
  Send,
  ShoppingCart,
  SproutIcon,
  Sun,
  TreePineIcon,
  X,
} from "lucide-react";

export const Icons = {
  logo: Carrot,
  search: Search,
  X: X,
  cart: ShoppingCart,
  menu: MenuIcon,
  heart: Heart,
  arrowRight: ArrowRight,
  leaf: LeafIcon,
  sprout: SproutIcon,
  tree: TreePineIcon,
  github: Github,
  fingerPrint: Fingerprint,
  send: Send,
  sun: Sun,
  chevronRight: ChevronRight,
  spinner: Disc,
};
